name: CD - Deploy Databricks Bundle
 
on:

  push:

    branches:

      - main
 
jobs:

  deploy:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout repository

        uses: actions/checkout@v4
 
      - name: Install Databricks CLI

        uses: databricks/setup-cli@main
 
      - name: Validate Databricks Bundle

        run: databricks bundle validate --target dev

        env:

          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
 
      - name: Deploy Databricks Bundle

        run: databricks bundle deploy --target dev

        env:

          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
 
      - name: Run Databricks Job

        run: databricks bundle run sample_job --target dev

        env:

          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
 