name: CI - Validate DAB
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  validate:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
 
      - name: Validate Databricks Bundle
        run: databricks bundle validate --target dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}